baseURL = 'https://thoughtp0lice.github.io/my_blog'
languageCode = 'en-us'
title = "Han and the Telescreen"
theme = "archie"

[params]
	mode="light"
	useCDN=false

[[menu.main]]
name = "About"
url = "/about"
weight = 3