baseURL = 'https://thoughtp0lice.github.io/my_blog/'
languageCode = 'en-us'
title = "Han and the Telescreen"
theme = "archie"
copyright = "Â© Han"
disqusShortname = "thought-police"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10 # articles per page

[params]
	mode="toggle"
	useCDN=false
	subtitle = "Literally 1984" 

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/thoughtp0lice"

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Round Table"
url = "/round_table"
weight = 2